sudo: required
services:
- docker
env:
  global:
  - IMAGE_NAME=damilink/meca
  - REGISTRY_USER=damilink
  - REGISTRY_PASS=miagelille
before_script:
- mvn install dockerfile:build
- docker pull "$IMAGE_NAME" || true
script:
- docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
after_script:
- docker images
addons:
  ssh_known_hosts: damien@51.75.140.39
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- openssl aes-256-cbc -K $encrypted_f5de63fc5559_key -iv $encrypted_f5de63fc5559_iv -in deploy_rsa_meca.enc -out /tmp/deploy_rsa_meca -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa_meca
- ssh-add /tmp/deploy_rsa_meca
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
before_install:

