language: java
dist: trusty
sudo: false
install: true

#addons:
#  sonarcloud:
#    organization: "creatingsolutions-github"
#    token:
#      secure: "VxEpTaHneXS1XdDrztoGp8oLaN40JcCUmR4QLZKBxPlcxFwXlDRsBXPodUeD6kbKR7gtDQVWbF3cW3Mxa5ibqPZkPfuQUiL0D0o8KudavXzt1uQOwHZlG2gJ7ZOeFDRJnoNJxfLiOzFxBbWVjZ+2AVr5XOoxnAQ2WXT9EV3t/FhPPEkibIGHT+utJNmO+LXK5Hq2HufVgJl9a99+T9essDj6Se8i/A69mzlxLtEgbngRiNY4JOKX7o1AFpuXySe7RagX7sJpvOOzabXfx0uNa5JozlL29SrTuN0H+Me+0DrYza/VhTDAsnUTHXJos4GwihQ91eVOcLAaCNW+IZN/r94emhIkrfQffEabnuIY6nxexgi7Gvbx3hoRxMRr3PY+F2yoy2ZkfGivpcKr1dMhbJViBJrFVKCZ0I+cWykYYRa8ku2gDSqbvoC+aP/ufuoYJuj8Z+HNKz0lBcC44NrBltLXzSTK6Y5wvodBlp9+rG32rMx6fqxklfOXYX+ZF0nZTUyUN8b9hIfnCMonNFnHg+/lTBAhNzvv6OKpaEdVLYNBbAtuVk2xIgmepG+JirBIGe6KStWWPbkAxu6MIP0r5nkdlKUUeSQTMHTzt3OhEfKP5L22mPtl2SO8/xKZnupWbmkUejSEndRPc2l1MYcYKB68+PAQlzi/c7KjC6tx0pg="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=webstation-api-meca -Dsonar.organization=creatingsolutions-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=42a81f23039b66c2dbefda914ef3c6b1cf4ccbbb

jdk:
- oraclejdk8

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
