version: '3'

services:
  mysql-docker-container:
    image: mysql:5.7.23
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=test
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    volumes:
    - /data/mysql
  meca:
    image: meca
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
    - mysql-docker-container
    ports:
    - 8087:8080
    volumes:
    - /data/spring-boot-app
