-- Jeune Alpin
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.1', '1/2 J', '20', FALSE, 'ALPIN', 'DEMI', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '1 J', '23.5', FALSE, 'ALPIN', 'ONE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '2 J', '44.7', FALSE, 'ALPIN', 'TWO', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '3 J', '67.00', FALSE, 'ALPIN', 'TREE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '4 J', '89.3', FALSE, 'ALPIN', 'FOUR', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '5 J', '111.7', FALSE, 'ALPIN', 'FIVE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '6 J', '123.1', FALSE, 'ALPIN', 'SIX', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '7 J', '139.9', FALSE, 'ALPIN', 'SEVEN', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '8 J', '156.7', FALSE, 'ALPIN', 'EIGHT', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', 'Forfait saison', '376', FALSE, 'ALPIN', 'SEASON', '0.0','0.0');

INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.1', '1/2 J', '23.2', TRUE, 'ALPIN', 'DEMI', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '1 J', '27.2', TRUE, 'ALPIN', 'ONE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '2 J',  '51.7', TRUE,'ALPIN', 'TWO', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '3 J',  '77.6',TRUE, 'ALPIN', 'TREE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '4 J',  '103.4',TRUE, 'ALPIN', 'FOUR', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '5 J',  '129.2',TRUE, 'ALPIN', 'FIVE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '6 J',  '142.4',TRUE, 'ALPIN', 'SIX', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '7 J',  '161.9',TRUE, 'ALPIN', 'SEVEN', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '8 J',  '181.4',TRUE, 'ALPIN', 'EIGHT', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', 'Forfait saison', '436',TRUE, 'ALPIN', 'SEASON', '0.0','0.0');

-- ADULTE Alpin
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.1', '1/2 J', '26', FALSE,'ALPIN', 'DEMI', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '1 J', '30.5',  FALSE,'ALPIN', 'ONE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '2 J', '58.0',  FALSE,'ALPIN', 'TWO', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '3 J', '87.0',  FALSE,'ALPIN', 'TREE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '4 J', '115.9',  FALSE,'ALPIN', 'FOUR', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '5 J', '144.9',  FALSE,'ALPIN', 'FIVE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '6 J', '159.7',  FALSE,'ALPIN', 'SIX', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '7 J', '181.5',  FALSE,'ALPIN', 'SEVEN', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '8 J', '203.3',  FALSE,'ALPIN', 'EIGHT', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', 'Forfait saison', '488',  FALSE,'ALPIN', 'SEASON', '0.0','0.0');

INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.1', '1/2 J', '30', TRUE,'ALPIN', 'DEMI', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '1 J',  '35.2', TRUE,'ALPIN', 'ONE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '2 J',  '66.9', TRUE,'ALPIN', 'TWO', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '3 J',  '100.4', TRUE,'ALPIN', 'TREE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '4 J',  '133.8', TRUE,'ALPIN', 'FOUR', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '5 J',  '167.2', TRUE,'ALPIN', 'FIVE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '6 J',  '184.3', TRUE,'ALPIN', 'SIX', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '7 J',  '209.5', TRUE,'ALPIN', 'SEVEN', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '8 J',  '234.7', TRUE,'ALPIN', 'EIGHT', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', 'Forfait saison',  '564', TRUE,'ALPIN', 'SEASON', '0.0','0.0');

-- SENIOR Alpin
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.1', '1/2 J', '23.4',  FALSE,'ALPIN', 'DEMI', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '1 J', '27.5',  FALSE,'ALPIN', 'ONE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '2 J', '52.3',  FALSE,'ALPIN', 'TWO', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '3 J', '78.4',  FALSE,'ALPIN', 'TREE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '4 J', '104.5',  FALSE,'ALPIN', 'FOUR', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '5 J', '130.7',  FALSE,'ALPIN', 'FIVE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '6 J', '144',  FALSE,'ALPIN', 'SIX', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '7 J', '163.7',  FALSE,'ALPIN', 'SEVEN', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '8 J', '183.4',  FALSE,'ALPIN', 'EIGHT', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', 'Forfait saison', '440',  FALSE,'ALPIN', 'SEASON', '0.0','0.0');

INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.1', '1/2 J',  '27', TRUE,'ALPIN', 'DEMI', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '1 J',  '31.7', TRUE,'ALPIN', 'ONE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '2 J', '60.3', TRUE,'ALPIN', 'TWO', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '3 J',  '90.4', TRUE,'ALPIN', 'TREE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '4 J',  '120.5', TRUE,'ALPIN', 'FOUR', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '5 J',  '150.6', TRUE,'ALPIN', 'FIVE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '6 J', '166', TRUE,'ALPIN', 'SIX', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '7 J', '188.7', TRUE,'ALPIN', 'SEVEN', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '8 J',  '211.4', TRUE,'ALPIN', 'EIGHT', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', 'Forfait saison', '508', TRUE,'ALPIN', 'SEASON', '0.0','0.0');

-- AGE_OR Alpin
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.1', '1/2 J', '20',  FALSE,'ALPIN', 'DEMI', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '1 J', '23.5',  FALSE,'ALPIN', 'ONE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '2 J', '44.7',  FALSE,'ALPIN', 'TWO', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '3 J', '67.00',  FALSE,'ALPIN', 'TREE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '4 J', '89.3',  FALSE,'ALPIN', 'FOUR', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '5 J', '111.7',  FALSE,'ALPIN', 'FIVE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '6 J', '123.1',  FALSE,'ALPIN', 'SIX', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '7 J', '139.9',  FALSE,'ALPIN', 'SEVEN', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '8 J', '156.7',  FALSE,'ALPIN', 'EIGHT', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', 'Forfait saison', '376', FALSE,'ALPIN', 'SEASON', '0.0','0.0');

INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.1', '1/2 J',  '23.2', TRUE,'ALPIN', 'DEMI', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '1 J',  '27.2', TRUE,'ALPIN', 'ONE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '2 J',  '51.7', TRUE,'ALPIN', 'TWO', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '3 J',  '77.6', TRUE,'ALPIN', 'TREE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '4 J',  '103.4', TRUE,'ALPIN', 'FOUR', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '5 J',  '129.2', TRUE,'ALPIN', 'FIVE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '6 J',  '142.4', TRUE,'ALPIN', 'SIX', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '7 J',  '161.9', TRUE,'ALPIN', 'SEVEN', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '8 J',  '181.4', TRUE,'ALPIN', 'EIGHT', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', 'Forfait saison', '436', TRUE,'ALPIN', 'SEASON', '0.0','0.0');

-- Ski Nordique
-- JEUNE Nordique
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.1', '1/2 J', '3.4', FALSE, 'NORDIQUE', 'DEMI', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '1 J', '5', FALSE, 'NORDIQUE', 'ONE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '2 J', '9', FALSE, 'NORDIQUE', 'TWO', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '3 J', '12.9', FALSE, 'NORDIQUE', 'TREE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '4 J', '16.2', FALSE, 'NORDIQUE', 'FOUR', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '5 J', '19', FALSE, 'NORDIQUE', 'FIVE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '6 J', '21.3', FALSE, 'NORDIQUE', 'SIX', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '7 J', '23.5', FALSE, 'NORDIQUE', 'SEVEN', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', '8 J', FALSE, FALSE, 'NORDIQUE', 'EIGHT', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'JEUNE', 'Jeunes : de 5 ans à 15 ans', '2.8', 'Forfait saison', '84.5', FALSE, 'NORDIQUE', 'SEASON', '0.0','0.0');

-- ADULTE NORDIQUE
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.1', '1/2 J', '7.3', FALSE, 'NORDIQUE', 'DEMI', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '1 J', '9', FALSE, 'NORDIQUE', 'ONE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '2 J', '17.4', FALSE, 'NORDIQUE', 'TWO', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '3 J', '25.9', FALSE, 'NORDIQUE', 'TREE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '4 J', '34.3', FALSE, 'NORDIQUE', 'FOUR', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '5 J', '42.7', FALSE, 'NORDIQUE', 'FIVE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '6 J', '51.2', FALSE, 'NORDIQUE', 'SIX', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '7 J', '58.5', FALSE, 'NORDIQUE', 'SEVEN', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', '8 J', FALSE, FALSE, 'NORDIQUE', 'EIGHT', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'ADULTE', 'Adultes : de + de 15 ans à moins de 65 ans ', '2.8', 'Forfait saison', '84.5', FALSE, 'NORDIQUE', 'SEASON', '0.0','0.0');

-- SENIOR NORDIQUE
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.1', '1/2 J', '6.7', FALSE, 'NORDIQUE', 'DEMI', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '1 J', '8.4', FALSE, 'NORDIQUE', 'ONE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '2 J', '16.9', FALSE, 'NORDIQUE', 'TWO', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans s', '2.8', '3 J', '24.7', FALSE, 'NORDIQUE', 'TREE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '4 J', '32.6', FALSE, 'NORDIQUE', 'FOUR', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '5 J', '4.5', FALSE, 'NORDIQUE', 'FIVE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '6 J', '48.4', FALSE, 'NORDIQUE', 'SIX', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '7 J', '55.1', FALSE, 'NORDIQUE', 'SEVEN', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', '8 J', FALSE, FALSE, 'NORDIQUE', 'EIGHT', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'SENIOR', 'Senior : de + de 65 ans à – de 75 ans ', '2.8', 'Forfait saison', '84.5', FALSE, 'NORDIQUE', 'SEASON', '0.0','0.0');

-- AGE_OR NORDIQUE
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.1', '1/2 J', '3.4', FALSE, 'NORDIQUE', 'DEMI', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '1 J', '5', FALSE, 'NORDIQUE', 'ONE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '2 J', '9', FALSE, 'NORDIQUE', 'TWO', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '3 J', '12.9', FALSE, 'NORDIQUE', 'TREE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '4 J', '16.2', FALSE, 'NORDIQUE', 'FOUR', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '5 J', '19', FALSE, 'NORDIQUE', 'FIVE', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '6 J', '21.3', FALSE, 'NORDIQUE', 'SIX', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '7 J', '23.5', FALSE, 'NORDIQUE', 'SEVEN', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', '8 J', FALSE, FALSE, 'NORDIQUE', 'EIGHT', '0.0','0.0');
INSERT INTO `meca_lift` (`id`, `age`, `description`, `insurrance`, `label`, `price`, `diamond`, `type`, `labeltype`,`price_group`, `price_unit`) VALUES (NULL, 'AGE_OR', 'Age d''Or : de + de 75 ans ', '2.8', 'Forfait saison', '84.5', FALSE, 'NORDIQUE', 'SEASON', '0.0','0.0');

